### ISSUE TITLE
Simple Mobile view

### ISSUE THREAD

**Issue by pinkeshbadjatiya** [felicity-iiith/felicity17-website#2]
Major changes include:
- Change the menu to a simpler one
- Replace the animating frames with simple static background (of the same theme)
- Make essential divs re-sizeable to fit mobile screen

**Comment by mukulhase** [comment]
When screen size drops below 900:
- Increase the size of the felicity board.
- Remove clouds
- Add bootstrap navbar for navigation
- Full-width container for content
- Put nav buttons in bootstrap grid instead. Perhaps use a drop down.
- Share buttons should be spaced out

**Comment by saganshul** [comment]
@pinkeshbadjatiya @mukulhase who is gonna do that :P ?

**Comment by pinkeshbadjatiya** [comment]
I think @mukulhase is the one who has to do it. :P

**Comment by mukulhase** [comment]
I don't think we need a separate site for mobile tho, that's old fashioned :P just putting a few @media queries for now.

**Comment by ParthKolekar** [comment]
@pinkeshbadjatiya don't be lazy. 

Always remember that you are not going to get a chance to make a felicity website every again.

**Comment by pinkeshbadjatiya** [comment]
@ParthKolekar Actually i am not supposed to be making the website. Currently mukul is assigned this task and he is doing it.

**Comment by saganshul** [comment]
Done!
