### ISSUE TITLE
swinging felicity title is coming up of aboutUS, sap ,Sponcers and contact popup  

### ISSUE THREAD

**Issue by shadaabsiddiqie** [felicity-iiith/felicity17-website#7]
![screenshot from 2017-01-06 18-17-11](https://cloud.githubusercontent.com/assets/19512141/21718307/a5a34b54-d43c-11e6-8e6c-3abf2909571e.png)
in firefox IN FIREFOX swinging felicity title is coming up of aboutUS, sap ,Sponcers and contact popup

**Comment by saganshul** [comment]
@shadaabsiddiqie It is already fixed. But it is not been updated on server yet because of some other issue.
We are updating the final one today itself.
